DataMedSci/pymchelper

README.rst, pymchelper/bdo2txt.py
=> Fix missing args in main method

README.rst, setup.py
=> setup.py improved, git installation works

.travis.yml, .travis/deploy_package.sh, .travis/install_linux.sh, README.rst
=> pypitest and gfortran deps removed

pymchelper/bdo2txt.py
=> Fixed merging of many files for 1-dimensional data

setup.py
=> missing requirements added

pymchelper/bdo2txt.py
=> fixed fortranformatter import

pymchelper/bdo2txt.py
=> New colorscale

wrapper/executor.py, wrapper/executor_example.py, wrapper/executor_exceptions.py, wrapper/set_tmax0.py, wrapper/shields_manager.py
If it's about limiting number of running shields - it was tried to do it basing on free memory. However,  I think that basing on number of threads in particular computer is better idea.
=> issue #9 Simple runner and manager which observe run shields

.travis.yml, appveyor.yml, setup.py
=> properly handling Windows end-line separators in setup.py

pymchelper/bdo2txt.py
=> version switch added

pymchelper/bdo2txt.py
=> geomap detector added

pymchelper/bdo2txt.py
=> merging fluka files added

pymchelper/bdo2txt.py
=> Trip dose rescaling

pymchelper/bdo2txt.py
=> fixed reading header of VOXSCORE

pymchelper/bdo2txt.py
One letter change to fix #39 and fix #54 .
=> Fix bad zdim in TRiPcube headers.

.travis/run_osx.sh, pymchelper/bdo2txt.py
=> verbose and quiet options added

pymchelper/writers/plots.py
=> Appending suffix only when needed

.travis.yml
=> Fix failing pip upload

.travis.yml, .travis/install_linux.sh, pymchelper/readers/fluka.py, pymchelper/readers/shieldhit.py, pymchelper/writers/trip98.py, requirements.txt, setup.py, tests/requirements-test.txt, tox.ini
=> empty units added to Fluka reader

.travis.yml, docs/technical.rst, tests/requirements-test.txt, tests/test_default_converter.py, tox.ini
=> coverage added

.travis/install_linux.sh
=> Cleaning requirements

.travis.yml, tox.ini
=> python 3.7 added

pymchelper/readers/fluka.py
=> missing detector title added, caused a problems with image writer

appveyor.yml
=> appveyor now runs test one-by-one to save memory

pymchelper/writers/plots.py
=> fixed wrong data reshaping in 2D plots

pymchelper/readers/shieldhit.py, pymchelper/writers/plots.py
=> LET units changed from MeV/cm to keV/um

pymchelper/detector.py, pymchelper/run.py, pymchelper/writers/plots.py, tests/test_shieldhit12a_generate.py
=> error estimation from multiple runs

pymchelper/writers/plots.py
=> Fixed double convertions

pymchelper/detector.py, pymchelper/readers/shieldhit.py, pymchelper/shieldhit/detector/geometry.py, pymchelper/writers/plots.py
=> new plotting order implementation

pymchelper/detector.py
Fixes #118 for me, but needs to be double checked whether the results are still OK.
=> Sum nstats

pymchelper/readers/shieldhit.py, pymchelper/run.py
=> Correct units when scaling with number of particles

pymchelper/run.py
=> Check if output dir exists prior execution

pymchelper/flair/Data.py, pymchelper/flair/common/bmath.py, pymchelper/flair/common/csg.py, requirements.txt, tests/test_converters.py, tests/test_fluka_generate.py
=> requirements updated with numpy 1.12 fix

pymchelper/writers/trip98.py
=> consistent units in DDD header and data

.travis.yml, .travis/install_linux.sh
=> Restrict setuptools version fot py3.2

.travis.yml, tox.ini
=> Restricted docutils version

pymchelper/detector.py
=> Fix wrong calculation of stderr

pymchelper/readers/shieldhit.py
=> Fix #177 and some other errors.

pymchelper/writers/trip98.py
=> Fix wrong attribute being set.

docs/technical.rst, tests/requirements-test.txt
=> Versioneer problem fixed

pymchelper/readers/shieldhit.py
=> added support for reading DPLANE data

.travis.yml, .travis/deploy_package.sh
=> travis pypi deploy section added

pymchelper/writers/shieldhit.py
=> enabled writing headers for cylindrical scorers

pymchelper/readers/shieldhit.py
=> Fix missing zone handler #201

pymchelper/run.py
=> Energy option required for DDD writer

tox.ini
=> disabling parallel sphinx

pymchelper/detector.py
=> create output directory if not existing

.travis.yml, appveyor.yml, tests/requirements-test.txt
=> Improved appveyor config

docs/excel_converter.rst, docs/index.rst, docs/user_guide.rst, pymchelper/detector.py, pymchelper/run.py, pymchelper/writers/excel.py, requirements.txt, tests/test_call_entry.py
=> Excel converter

pymchelper/readers/fluka.py, pymchelper/readers/shieldhit.py, pymchelper/writers/plots.py, tox.ini
=> plotting axes names

pymchelper/detector.py, pymchelper/run.py, requirements.txt, tox.ini
=> parallel output generation

tests/requirements-test.txt, tox.ini
=> restricting pytest-xdist for python 3.2

pymchelper/writers/plots.py
=> missing label settings added

pymchelper/readers/shieldhit.py
=> Fix normalization issue #241 for Q scorer

pymchelper/readers/shieldhit.py
=> Q unit is now dimensionless

pymchelper/detector.py, tests/test_call_entry.py
=> fixed group recognition when bdo files resides in different directories.

pymchelper/readers/shieldhit.py
=> new tag introduced

docs/inspect_converter.rst, docs/user_guide.rst, pymchelper/detector.py, pymchelper/run.py, pymchelper/writers/inspector.py
=> new inspector writer

docs/inspect_converter.rst, pymchelper/run.py, pymchelper/writers/inspector.py
=> improved printing and small fixes in the documentation

.travis.yml, docs/user_guide.rst, examples/comparison.py, pymchelper/detector.py, pymchelper/io.py, pymchelper/readers/common.py, pymchelper/readers/fluka.py, pymchelper/readers/shieldhit.py, pymchelper/run.py, pymchelper/writers/common.py, pymchelper/writers/excel.py, pymchelper/writers/inspector.py, pymchelper/writers/plots.py, pymchelper/writers/shieldhit.py, pymchelper/writers/sparse.py, pymchelper/writers/trip98.py, pytest.ini, tests/test_converters.py, tests/test_default_converter.py, tests/test_shieldhit12a_generate.py
Fixes #259 , #237 , #232 
This PR has started as bugfix of #259 , but in the course of fixing it, I decided to rework completely a detector class structure.
The aim was to provide some simple API for readers and writer class and simplify processing of input files/directories
=> detector class major rework

pymchelper/readers/shieldhit.py
=> reading files with logaritmic binning

pymchelper/readers/shieldhit.py
=> fixed LET units on differential scoring

pymchelper/flair/Data.py, pymchelper/readers/fluka.py
=> first attempt of usrtrack implementation

pymchelper/flair/Input.py, pymchelper/flair/common/bmath.py, pymchelper/flair/common/csg.py, pymchelper/flair/common/rexx.py, pymchelper/utils/pld2sobp.py
most of the raised by new version of flake8
Fixes #269
=> several new pep8 problems fixed

.travis/install_linux.sh
=> limit py version as starting from 1.5 support for python 3.3 is dropped

.travis.yml, setup.py, tox.ini
=> dropping support for python3.3 and some minor setup.py cleaning

.travis.yml, appveyor.yml, setup.py
=> adjusted to new API of pkg_resources in setuptools package

pymchelper/io.py
with picliking when using joblib library
Fixes #297
=> nested function replaced with global ones to avoid problems

pymchelper/detector.py, pymchelper/readers/shieldhit.py, pymchelper/writers/plots.py, tests/requirements-test.txt
=> correct axis formatting and data arrangement for differentail scoring

pymchelper/writers/excel.py
=> Fixed error column handling

pymchelper/io.py, pymchelper/run.py, pymchelper/writers/excel.py, pymchelper/writers/inspector.py, pymchelper/writers/plots.py, pymchelper/writers/shieldhit.py, pymchelper/writers/sparse.py, pymchelper/writers/trip98.py
improved options and status code handling
Fixes #309
=> data reshaping improved for DDD detector

pymchelper/run.py, pymchelper/writers/trip98.py
=> DDD: Energy and projectile reading from BDO data

pymchelper/writers/trip98.py
=> fixed material name

pymchelper/writers/trip98.py
=> setting DDD tail cut value via environmental variable

pymchelper/writers/trip98.py
=> improved error checking on 2 gaussian fit in DDD writer

tests/requirements-test.txt
=> old tox for python 3.2

.travis.yml, appveyor.yml
=> Fix appveyor

pymchelper/readers/shieldhit.py
Added `per nucleon` which fixes #339
=> Fixed kinetic energy units

.travis/deploy_package.sh, setup.py
=> improved packaging

pymchelper/__init__.py
=> improved versioning for python2

pymchelper/utils/mcscripter.py
=> fix output not being written when no loops defined.

pymchelper/readers/shieldhit/binary_spec.py
=> more data read from BDO files

pymchelper/writers/plots.py
=> multiple PNG files for multiple pages output

pymchelper/readers/shieldhit/binary_spec.py
=> new bdo tags added

pymchelper/readers/shieldhit/binary_spec.py, pymchelper/run.py, pymchelper/writers/common.py, pymchelper/writers/trip98.py, pymchelper/writers/trip98cube.py, pymchelper/writers/trip98ddd.py
=> improved support for TRiP98 BDO tags

pymchelper/readers/fluka.py, pymchelper/readers/shieldhit/reader_bdo2016.py, pymchelper/readers/shieldhit/reader_bdo2019.py, pymchelper/readers/shieldhit/reader_bin2010.py
=> Fix for missing pages data struct in bdo2016 reader

.travis.yml
added optional build target - python 3.8
=> added new password to pypi

.travis.yml, appveyor.yml, setup.py, tox.ini
=> python 3.8 and 3.9 tests

pymchelper/readers/shieldhit/reader_bdo2016.py, pymchelper/readers/shieldhit/reader_bdo2019.py
=> add missing pages

pymchelper/readers/shieldhit/reader_bdo2019.py, pymchelper/writers/plots.py
=> fixed wrongly spelled attribute for diff units

pymchelper/estimator.py
=> data arrangment

README.rst, pymchelper/executor/runner.py
=> documenting usage of _pool._processes

examples/scripting_sh12a_run.py, setup.py
=> first round of comments

.github/workflows/python-app.yml
=> code analysis removed

examples/scripting_sh12a_run.py, pymchelper/executor/runner.py, pymchelper/utils/runmc.py, tests/test_runner.py
=> Runner refactoring

pymchelper/readers/shieldhit/reader_base.py, pymchelper/readers/shieldhit/reader_bdo2016.py, pymchelper/readers/shieldhit/reader_bdo2019.py, pymchelper/readers/shieldhit/reader_bin2010.py
=> fix axis names for 2019 file format

.github/workflows/python-app.yml
=> Fix syntax in GHA config

pymchelper/shieldhit/detector/detector_type.py
=> new SH12A detector types added

pymchelper/readers/shieldhit/reader_base.py
=> fix deprecated check for empty array

.github/workflows/python-app.yml, .gitignore, Dockerfile, convertmc.spec, run.spec
=> Shrink size of `convertmc` executable generated with pyinstaller

debian_packages/single_file_executables/convertmc.spec
=> Fix for conflicting external libraries when saving PNG files using deb-installed convertmc

docs/images_generation/run.sh
bump shieldhit demo version to 1.0.0
=> v2.2.2 fixes

.github/workflows/release-pip.yml
Needed to publish docs to github pages
=> better permissions for github token

pymchelper/writers/json.py, tests/test_json.py
PR is conducted by problems on UI with proper naming convertion
=> Naming update for json convertion

.github/workflows/python-app.yml, pymchelper/utils/radiotherapy/plan.py
=> Fix mistaking highest and lowest energy in plan diagnostics summary

pymchelper/executor/runner.py, pymchelper/simulator_type.py, pymchelper/utils/runmc.py, tests/test_runner.py
Resolves https://github.com/yaptide/yaptide/issues/402
=> 402 update fluka support

.deepsource.toml, .github/workflows/python-app.yml, .github/workflows/release-deb.yml, README.md, debian_packages/single_file_executables/convertmc.spec, debian_packages/single_file_executables/runmc.spec, pymchelper/flair/Input.py
This pull request includes several updates to configuration files, documentation, and code improvements in the `pymchelper` project. The most important changes include updates to the GitHub Actions workflow, adjustments to the `.deepsource.toml` configuration, enhancements to the installation instructions in the `README.md`, and multiple code formatting improvements in the `Input.py` file.
* [`.deepsource.toml`](diffhunk://#diff-a8c050b1fb601cdd8ba1282e837bc0b553d4f83de74d151e52f415b4e1ed6d14R9-R11): Added `exclude_patterns` to exclude specific files from analysis.
* [`.github/workflows/release-deb.yml`](diffhunk://#diff-53e0e1759d62bb2c60e86f9bf16cdcc99048213ea883af7900ffb7ddf2fd4655L8-R8): Updated the branches to include `master` for pull requests and modified the Docker tags for the …
=> single package executables

.github/dependabot.yml, .github/workflows/python-app.yml, .github/workflows/release-pip.yml, docs/conf.py, docs/requirements.txt
This pull request includes several changes to the configuration and documentation files to improve the build and deployment processes, as well as to update dependencies.
Configuration updates:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R17-R21): Added a new `package-ecosystem` for `pip` in the `/docs/` directory to schedule daily updates.
Workflow improvements:
* [`.github/workflows/release-pip.yml`](diffhunk://#diff-62e08f6ea3fada8a4f09403aa7de4753ac6452b74280e302936855e2b7257accL79-R82): Modified the `jobs` section to correct the `packages-dir` key, add the `print-hash` option, and update the artifact upload process to use `actions/upload-pages-artifact@v3`. [[1]](diffhunk://#diff-62e08f6ea3fada8a4f09403aa7de4753ac6452b74 …
=> improve github pages deploy

pymchelper/run.py, pymchelper/writers/shieldhit.py
This pull request includes several changes to the `pymchelper` project, focusing on enhancing the functionality of the `run.py` script and improving the `shieldhit.py` writer. The most important changes include adding and removing subparsers in the `run.py` file and updating the `write` method in the `shieldhit.py` file to include error handling for unsupported file formats.
Changes to `run.py`:
* Added a subparser for `plotdata` conversion to the `main` function.
* Removed the previously added `plotdata` subparser from the `main` function to avoid redundancy.
Changes to `shieldhit.py`:
* Imported the `Estimator` class from `pymchelper.estimator`.
* Updated the `write` method to include type hinting for the `estimator` parameter and added error handling for unsupported file formats.
=> txt converter update
